routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/Login', function () {
    return view('Login');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->group(function(){
	Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
	Route::post('/login','Auth\AdminLoginController@login')->name('admin.login.submit');
	Route::get('/', 'AdminController@index')->name('admin');
});
Route::prefix('staff')->group(function(){
	Route::get('/login','Auth\StaffLoginController@showLoginForm')->name('staff.login');
	Route::post('/login','Auth\StaffLoginController@login')->name('staff.login.submit');
	Route::get('/', 'StaffController@index')->name('staff');

});
Route::prefix('nuser')->group(function(){
	Route::get('/login','Auth\NuserLoginController@showLoginForm')->name('nuser.login');
	Route::post('/login','Auth\NuserLoginController@login')->name('nuser.login.submit');
	Route::get('/', 'NuserController@index')->name('nuser');
	//reset password 
	
	Route::post('/password/email', 'Auth\NuserForgotPasswordController@sendResetLinkEmail')->name('nuser.password.email');
  	Route::get('/password/reset', 'Auth\NuserForgotPasswordController@showLinkRequestForm')->name('nuser.password.request');
  Route::post('/password/reset', 'Auth\NuserResetPasswordController@reset');
  Route::get('/password/reset/{token}', 'Auth\NuserResetPasswordController@showResetForm')->name('nuser.password.reset');

});
Route::prefix('auser')->group(function(){
	Route::get('/login','Auth\AuserLoginController@showLoginForm')->name('auser.login');
	Route::post('/login','Auth\AuserLoginController@login')->name('auser.login.submit');
	Route::get('/', 'AuserController@index')->name('auser');
	//reset password 

	Route::post('/password/email', 'Auth\AuserForgotPasswordController@sendResetLinkEmail')->name('auser.password.email');
  	Route::get('/password/reset', 'Auth\AuserForgotPasswordController@showLinkRequestForm')->name('auser.password.request');
  Route::post('/password/reset', 'Auth\AuserResetPasswordController@reset');
  Route::get('/password/reset/{token}', 'Auth\AuserResetPasswordController@showResetForm')->name('auser.password.reset');

});

Route::resource('query','queryController');
Route::resource('adminQuery','adminQueryController');
Route::resource('adminTask','adminTasksController');
Route::resource('task','taskController');

//Staff Rout File

Route::resource('staffs/querys','queryStaffController');
Route::resource('staffs/taskStaffUpdate','TaskStaffController');
Route::resource('staffs/progress_report','progress_reportController');

// Basic User File Control Rout
Route::resource('nusers/queryes','queryNuserController');

//Advanced User Routs
Route::resource('ausers/query','queryAuserController');
Route::resource('ausers/task','TaskAuserController');
Route::resource('ausers/primiumInformation','primiumInformationController');


Route::resource('Information','InformationController');
Route::resource('Service','ServiceController');
Route::resource('Team_member','Team_memeberController');
Route::resource('Normal_user','NormaluserController');
Route::resource('Advanced_user','AdvancedUserController');
Route::resource('Staff_user','StaffUserController');
Route::resource('clineTask','ClineTaskController');


// Cline Assign Route 

Route::resource('cline_assign','ClineAssignController');

//Advanced User Register
Route::resource('aregister','aRegistationController');

//Basic User Registation

Route::resource('nregister','nRegistationController');



Route::get('/email','clineTaskController@email')->name('email');
Route::get('/email','AdminController@email')->name('sendEmail');
Route::get('/email','TaskAuserController@email')->name('sendEmail');
Route::get('/verifyEmailFirst','aRegistationController@verifyEmailFirst')->name('verifyEmailFirst');
Route::get('verify/{email}/{verifyTocken}','aRegistationController@sendEmailDone')->name('sendEmailDone');

//Register Redirect page

Route::get('auth.auser-login','Auth\AuserLoginController@showLoginForm')->name('auth.auser-login');


//Frontend Route Start hear ----

Route::get('/', function () {
    return view('index');
});
Route::get('/about' , 'siteController@about');
Route::get('/contact','siteController@contact');
Route::get('/service','siteController@service');
Route::get('/planeTable','siteController@planeTable');

resources/views/admin.blade.php
@include('admin.app')
<div class="col-sm-6 " style="width: 300px;">

        <h3>Staff & Cline</h3>
        

        
@foreach($staffinfo as $staffinfos)
<h4 style="color: green">{{$staffinfos->name}}</h4>
@foreach($cline as $clines)
<?php $staff_id=$staffinfos->id;
                                            $cline_id=$clines->staff_id;

                                             if ($staff_id==$cline_id) {
                                     ?> 
<ul style="color: red">
  <li >{{$clines->staff_name}}</li>

</ul>  
<?php }?>

                                        @endforeach 
@endforeach
<a href="{{ route('cline_assign.index') }}" class="btn btn-primary btn-lg primary" role="button" aria-pressed="true" style="font-size: 10px;">See More... </a>

</div>
<div class="col-sm-3 col-md-6">

        <h3 align="cemter" style="color: green">System Overview</h3>
        <table class="table">
            <tbody>
                <tc>
                    <td style="color: green">Query </td>
                    <td style="color: red">100</td>
                </tc>
            </tbody>
            <tbody>
                <tc>
                    <td style="color: green">Task </td>
                    <td style="color: red">100</td>
                </tc>
            </tbody>
            <tbody>
                <tc>
                    <td style="color: green">Basic User </td>
                    <td style="color: red">10</td>
                </tc>
            </tbody>
            <tbody>
                <tc>
                    <td style="color: green">Premium User </td>
                    <td style="color: red">10</td>
                </tc>
            </tbody>

            <tbody>
                
                <td style="color: green">Staff</td>
                <td style="color: red">200</td>
            </tbody>

            </tbody>
            
        </table>
        <div class="col-sm-6 " style="width: 300px;">

        <h3>Staff & Task</h3>
        

        
@foreach($staffinfo as $staffinfos)
<h5 style="color: green">{{$staffinfos->name}}</h5>
<?php $staff_id=$staffinfos->email; ?>
@foreach($task as $tasks)
                                     <?php 
                                            $cline_id=$tasks->Staff_Id;
                                            $dec=strcmp($staff_id, $cline_id);

                                             if ($dec==0) {
                                     ?> 
<ul style="color: red">
  <li >{{$tasks->file_name}}</li>

</ul>  
<?php }?>

                                        @endforeach 
@endforeach
<a href="{{ route('adminTask.index') }}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" style="font-size: 10px;">See More... </a>

</div>
</div>
<div class="col-sm-3 col-md-6" style="width:100% ">

        
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <th style="color: green">Task</th>
                <th style="color: green">Cline ID</th>
                <th style="color: green">Create Date</th>
            </thead>
            <tbody>
                @foreach($task as $tasks)
                
                <?php 
                $descigin=$tasks->status;
                if ($descigin=='completed') {?>
                    <tr style="background-color: #c4d832">
                                <?php
                                    
                                     ?>
                                    <th>{{$tasks->file_name}}</th>
                                    <th>{{$tasks->email}}</th>
                                    <th>{{date($tasks->created_at)}}</th>
                
                                </tr>
                    
                <?php } else{ ?>
                    <tr style="background-color: #96efe7">
                                    <th>{{$tasks->file_name}}</th>
                                    <th>{{$tasks->email}}</th>
                                    <th>{{{date('M j, Y', strtotime($tasks->created_at))}}}</th>
                                    
                                </tr>
                <?php }
                ?>
                                
                @endforeach
            </tbody>
            
        </table>
        <a href="{{ route('task.index') }}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true" style="font-size: 10px;">See More... </a>
        
    </div>
</div>
<a href="{{route('sendEmail')}}" class="btn bth-block bth-primary">Send An email</a>
@include('admin-layout.footer')

resources/views/auser.blade.php
@include('ausers/auser.app')
<div class="row">
	<div class="col-md-10">
		<h3 style="color: green">All Query List</h3>
	</div>

	<hr>

</div>
<div class="row">
	<div class="col-md-12">
		<table class="table">
			<thead>
				<th>Sn</th>
				<th>Query Name</th>
				<th>Create Date</th>
				<th>Action</th>
			</thead>
			<tbody>
				@foreach($query as $querys)

				<?php
				$putcolor=$querys->answer;
				if (empty($putcolor)) {?>
				 	<tr style="background-color: #96efe7">
					<th>{{$querys->id}}</th>
					<th>{{$querys->question}}</th>
					<td>{{date('M j, Y', strtotime($querys->created_at))}}</td>
					<td><a href="{{route('query.edit',$querys->id)}}" class="btn btn-primary a-btn-slide-text"> <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        <span><strong>Update</strong></span> </a><a href="{{route('query.show',$querys->id)}}" style="margin: 10px;" class="btn btn-primary a-btn-slide-text"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <span><strong>View</strong></span> </a></td>
				</tr>
				
				<?php  } 

				 else  {?>

				 	<tr style="background-color: #c4d832">
					<th>{{$querys->id}}</th>
					<th>{{$querys->question}}</th>
					<td>{{date('M j, Y', strtotime($querys->created_at))}}</td>
					<td><a href="{{route('query.show',$querys->id)}}" style="margin: 10px;" class="btn btn-primary a-btn-slide-text"> <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <span><strong>View</strong></span></a></td>

				<?php } ?>
				
				@endforeach
			</tbody>
			
		</table>
		
	</div>
</div>
<div class="row">
	<div class="col-md-10">
		<h3 style="color: green">All Task List</h3>
	</div>
	
	<hr>

</div>
<div class="row">
	<div class="col-md-12">
		<table class="table">
			<thead>
				<th>Sn</th>
				<th>Task</th>
				<th>Cline ID</th>
				<th>Create Date</th>
			</thead>
			<tbody>
				@foreach($task as $tasks)
				
				<?php 
				$descigin=$tasks->status;
				if ($descigin=='completed') {?>
					<tr style="background-color: #c4d832">
								<?php
									
									 ?>

									<th>{{$tasks->id}}</th>
									<th>{{$tasks->file_name}}</th>
									<th>{{$tasks->email}}</th>
									<th>{{date($tasks->created_at)}}</th>
									<th><a href="" style="padding-right: 8px">Delete</a></th>
								</tr>
					
				<?php } else{ ?>
					<tr style="background-color: #96efe7">
									<th>{{$tasks->id}}</th>
									<th>{{$tasks->file_name}}</th>
									<th>{{$tasks->email}}</th>
									<th>{{{date('M j, Y', strtotime($tasks->created_at))}}}</th>
									<th> 
										 <a href="{{route('task.show',$tasks->id)}}" style="margin: 10px;"  class="btn btn-primary a-btn-slide-text">  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <span><strong>View</strong></span></a>
        <a href="{{route('task.edit',$tasks->id)}}" class="btn btn-primary a-btn-slide-text"> <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        <span><strong>Update</strong></span> </a>
									</th>
								</tr>
				<?php }
				?>
								
				@endforeach
			</tbody>
			
		</table>
		
	</div>
</div>

 @include('staffs/staff_layout.footer')

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('frontends.app')

@section('content')

<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{{asset('/')}}" style="color: #DF0101">Audit Form </a>
        <button class="navbar-toggler navbar-toggler-center" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">

                <div class="dropdown">
                <button class="dropbtn" style="color: #01DF3A">REGISTER</button>
                <div class="dropdown-content">
                  <a href="#">Basic User</a>
                  <a href="#">Primium User</a>
                </div>
                </div>

            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{{asset('service')}}" style="color: #01DF3A">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{{asset('about')}}" style="color: #01DF3A">About</a>
            </li>
             <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{{asset('planeTable')}}" style="color: #01DF3A">Service Type</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{{asset('contact')}}" style="color: #01DF3A">Contact</a>
            </li>
            <div class="dropdown">
                <button class="dropbtn" style="color: #01DF3A">LOGIN</button>
                <div class="dropdown-content">
                 <a href="{{asset('nuser')}}">Basic User</a>
                  <a href="{{asset('auser')}}">Primium User</a>
                </div>
                </div>
          </ul>
        </div>
      </div>
    </nav>
  

    <!-- Header Video Start hear  -->
      
      <div class="header-container">

    <div class="video-container">
      <video preload="true" autoplay="autoplay" loop="loop"  volume="0" poster="pic.jpg">
          
        <source src="asset/video/OfficeTeam.mp4" type="video/mp4">
          <source src="asset/video/test.webm" type="video/webm">
            <source src="asset/video/test.ogv" type="video/ogg">
      </video>

      
    </div>        

  </div>



  @endsection

resources/views/main.blade.php
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Audit Form</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 12px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
            <div class="content">
                <div class="title m-b-md">
                    @section('content')
                </div>

            </div>
        </div>
    </body>
</html>

resources/views/nuser.blade.php
@include('nusers/nuser.app')
<div class="row">
	<div class="col-md-10">
		<h3 style="color: green">All Query List</h3>
	</div>
	<div class="col-md-2">
		<a href="{{ url('nusers/queryes/create') }}" class="bth bth-lg bth-block bth-primary" style="font-size: 15px;" class="btn btn-primary a-btn-slide-text"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        <span><strong>Create</strong></span> </a>
	</div>
	<hr>

</div>
<div class="row">
	<div class="col-md-12">
		<table class="table">
			<thead>
				<th>Sn</th>
				<th>Query Name</th>
				<th>Create Date</th>
				<th>Action</th>
			</thead>
			<tbody>
				@foreach($query as $querys)

				<?php
				$putcolor=$querys->answer;
				if (empty($putcolor)) {?>
				 	<tr style="background-color: #96efe7">
					<th>{{$querys->id}}</th>
					<th>{{$querys->question}}</th>
					<td>{{date('M j, Y', strtotime($querys->created_at))}}</td>
					<td><a href="{{route('queryes.edit',$querys->id)}}" class="btn btn-primary a-btn-slide-text"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        <span><strong>Update</strong></span></a><a href="{{route('queryes.show',$querys->id)}}" style="margin: 10px;" class="btn btn-primary a-btn-slide-text"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <span><strong>View</strong></span></a></td>
				</tr>
				
				<?php  } 

				 else  {?>

				 	<tr style="background-color: #c4d832">
					<th>{{$querys->id}}</th>
					<th>{{$querys->question}}</th>
					<td>{{date('M j, Y', strtotime($querys->created_at))}}</td>
					<td><a href="{{route('queryes.show',$querys->id)}}" style="margin: 10px;" class="btn btn-primary a-btn-slide-text"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <span><strong>View</strong></span></a></td>

				<?php } ?>
				
				@endforeach
			</tbody>
			
		</table>
		
	</div>
</div>
 @include('nusers/nuser_layout.footer')

resources/views/staff.blade.php
@include('staffs/staff.app')
   <div class="row">
	<div class="col-md-10">
		<h3 style="color: green">All Progress Report</h3>
	</div>
	
	<hr>

</div>
<div class="row">
	<div class="col-md-12">
		<table class="table">
			<thead>
				<th>Sn</th>
				<th>Task Name</th>
				<th>Status</th>
				<th>Create Date</th>
				<th>Action</th>
			</thead>
			<tbody>
				@foreach($progressReport as $progress_reports)

				<?php
				$putcolor=$progress_reports->status;
				if ($putcolor=="In progress") {?>
				 	<tr style="background-color: #96efe7">
					<th>{{$progress_reports->id}}</th>
					<th>{{$progress_reports->task_name}}</th>
					<td>{{$progress_reports->status}}</td>
					<td>{{date('M j, Y', strtotime($progress_reports->created_at))}}</td>
					<td><a href="{{route('progress_report.edit',$progress_reports->id)}}" style="padding-right: 8px" class="btn btn-primary a-btn-slide-text">
						 <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        <span><strong>Update</strong></span> 
					</a><a href="../storage/upload/{{$progress_reports->file}}" download="{{$progress_reports->file }}" class='ng-button'><i class="fa fa-download"></i>Download</a></td>
				</tr>
				
				<?php  } 

				 elseif ($putcolor=="Not started") {?>

				 	<tr style="background-color: #ed1b31">
					<th>{{$progress_reports->id}}</th>
					<th>{{$progress_reports->task_name}}</th>
					<td>{{$progress_reports->status}}</td>
					<td>{{date('M j, Y', strtotime($progress_reports->created_at))}}</td>
					<td><a href="{{route('progress_report.edit',$progress_reports->id)}}" style="padding-right: 8px" class="btn btn-primary a-btn-slide-text"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        <span><strong>Update</strong></span> </a><a href="../storage/upload/{{$progress_reports->file}}" download="{{$progress_reports->file }}" class='ng-button'> <i class="fa fa-download"></i>Download</a></td>

				<?php }
				 elseif ($putcolor=="Complete") {?>
				 	<tr style="background-color: #c4d832">
					<th>{{$progress_reports->id}}</th>
					<th>{{$progress_reports->task_name}}</th>
					<td>{{$progress_reports->status}}</td>
					<td>{{date('M j, Y', strtotime($progress_reports->created_at))}}</td>
					<td><a href="../storage/upload/{{$progress_reports->file}}" download="{{$progress_reports->file }}" class='ng-button'> <i class="fa fa-download"></i>Download</a></td>
				<?php  }
				 else{
				 	echo "";
				 }
				?>
				
				@endforeach
			</tbody>
			
		</table>
		
	</div>
</div>
<div class="row">
	<div class="col-md-10">
		<h3 style="color: green">All Task </h3>
	</div>
	
	<hr>

</div>
<div class="row">
	<div class="col-md-12">
		<table class="table">
			<thead>
				<th>Sn</th>
				<th>Task</th>
				<th>Cline ID</th>
				<th>Create Date</th>
				<th>Attach file</th>
			</thead>
			<tbody>
				@foreach($task as $tasks)
				
				<?php 
				$old_time=strtotime($tasks->endtaskdate);
				$current_time=date('Y/m/d');
				$currents_time=strtotime($current_time);
				$different=$currents_time-$old_time;
				$dates=($different/(60*60*24));
				if ($dates>'2') {?>
					<tr style="background-color: #ed1b31">
								<?php
									
									 ?>

									<th>{{$tasks->id}}</th>
									<th>{{$tasks->file_name}}</th>
									<th>{{$tasks->email}}</th>
									<th>{{date($tasks->created_at)}}</th>

									<td><a href="../storage/upload/{{$tasks->file}}" download="{{$tasks->file }}">Download</a></td>
									
								</tr>
					
				<?php } else{ ?>
					<tr style="background-color: #c4d832">
									<th>{{$tasks->id}}</th>
									<th>{{$tasks->file_name}}</th>
									<th>{{$tasks->email}}</th>
									<th>{{{date('M j, Y', strtotime($tasks->created_at))}}}</th>
									<td><a href="../storage/upload/{{$tasks->file}}" download="{{$tasks->file }}" class='ng-button'> <i class="fa fa-download"></i>Downlaod</a></td>
									
								</tr>
				<?php }
				?>
								
				@endforeach
			</tbody>
			
		</table>
		
	</div>
</div>

 @include('staffs/staff_layout.footer')