routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/Login', function () {
    return view('Login');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::prefix('admin')->group(function(){
	Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
	Route::post('/login','Auth\AdminLoginController@login')->name('admin.login.submit');
	Route::get('/', 'AdminController@index')->name('admin');
});
Route::prefix('staff')->group(function(){
	Route::get('/login','Auth\StaffLoginController@showLoginForm')->name('staff.login');
	Route::post('/login','Auth\StaffLoginController@login')->name('staff.login.submit');
	Route::get('/', 'StaffController@index')->name('staff');

});
Route::prefix('nuser')->group(function(){
	Route::get('/login','Auth\NuserLoginController@showLoginForm')->name('nuser.login');
	Route::post('/login','Auth\NuserLoginController@login')->name('nuser.login.submit');
	Route::get('/', 'NuserController@index')->name('nuser');
	//reset password 
	
	Route::post('/password/email', 'Auth\NuserForgotPasswordController@sendResetLinkEmail')->name('nuser.password.email');
  	Route::get('/password/reset', 'Auth\NuserForgotPasswordController@showLinkRequestForm')->name('nuser.password.request');
  Route::post('/password/reset', 'Auth\NuserResetPasswordController@reset');
  Route::get('/password/reset/{token}', 'Auth\NuserResetPasswordController@showResetForm')->name('nuser.password.reset');

});
Route::prefix('auser')->group(function(){
	Route::get('/login','Auth\AuserLoginController@showLoginForm')->name('auser.login');
	Route::post('/login','Auth\AuserLoginController@login')->name('auser.login.submit');
	Route::get('/', 'AuserController@index')->name('auser');
	//reset password 

	Route::post('/password/email', 'Auth\AuserForgotPasswordController@sendResetLinkEmail')->name('auser.password.email');
  	Route::get('/password/reset', 'Auth\AuserForgotPasswordController@showLinkRequestForm')->name('auser.password.request');
  Route::post('/password/reset', 'Auth\AuserResetPasswordController@reset');
  Route::get('/password/reset/{token}', 'Auth\AuserResetPasswordController@showResetForm')->name('auser.password.reset');

});

Route::resource('query','queryController');
Route::resource('adminQuery','adminQueryController');
Route::resource('adminTask','adminTasksController');
Route::resource('task','taskController');

//Staff Rout File

Route::resource('staffs/querys','queryStaffController');
Route::resource('staffs/taskStaffUpdate','TaskStaffController');
Route::resource('staffs/progress_report','progress_reportController');

// Basic User File Control Rout
Route::resource('nusers/queryes','queryNuserController');

//Advanced User Routs
Route::resource('ausers/query','queryAuserController');
Route::resource('ausers/task','TaskAuserController');
Route::resource('ausers/primiumInformation','primiumInformationController');


Route::resource('Information','InformationController');
Route::resource('Service','ServiceController');
Route::resource('Team_member','Team_memeberController');
Route::resource('Normal_user','NormaluserController');
Route::resource('Advanced_user','AdvancedUserController');
Route::resource('Staff_user','StaffUserController');
Route::resource('clineTask','ClineTaskController');


// Cline Assign Route 

Route::resource('cline_assign','ClineAssignController');

//Advanced User Register
Route::resource('aregister','aRegistationController');

//Basic User Registation

Route::resource('nregister','nRegistationController');



Route::get('/email','clineTaskController@email')->name('email');
Route::get('/email','AdminController@email')->name('sendEmail');
Route::get('/email','TaskAuserController@email')->name('sendEmail');
Route::get('/verifyEmailFirst','aRegistationController@verifyEmailFirst')->name('verifyEmailFirst');
Route::get('verify/{email}/{verifyTocken}','aRegistationController@sendEmailDone')->name('sendEmailDone');

//Register Redirect page

Route::get('auth.auser-login','Auth\AuserLoginController@showLoginForm')->name('auth.auser-login');


//Frontend Route Start hear ----

Route::get('/', function () {
    return view('index');
});
Route::get('/about' , 'siteController@about');
Route::get('/contact','siteController@contact');
Route::get('/service','siteController@service');
Route::get('/planeTable','siteController@planeTable');

app/Query.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Query extends Authenticatable
{
    use Notifiable;
    protected $guard='query';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'question', 
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Staff.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Staff extends Authenticatable
{
    public function cline_assign(){
        return $this->hasMany(cline_assign::class);
    }
    use Notifiable;
    protected $guard='staff';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Staff;
use Illuminate\Support\Facades\DB;
use App\progress_report;
use App\Task;


class StaffController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:staff');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(){
                $email=session()->get('user_name');
        //$progressReport=DB::select('select * from progress_reports where create_by = ?', [$email]);
        $progressReport = DB::table('progress_reports')->where('create_by', $email)->paginate(5);

        //$task=DB::select('select * from tasks where Staff_Id = ?', [$email]);
        $task = DB::table('tasks')->where('Staff_Id', $email)->paginate(5);

        return view('staff')
        ->withprogressReport($progressReport)
        ->with('task',$task);
    }
}

app/Http/Controllers/queryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Query;
use DB;

class queryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $query  = DB::table('queries')->simplePaginate(5);
        return view('admins.query.index')->withTask($query);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('query.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validate form
        $this ->Validate($request , array(
            'question' =>'required| max:300'
        ));
        //Store database
        $query = new Query;
        $query->question = $request->question;
        $query->email=session()->get('user_name');
        $query->save();
        //Redirect Other page
        // return redirect()->route('query.show',$query->id);
        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $query=Query::find($id);

        return redirect()->route('admins.query.show')
        ->with('query' , $query);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Query::find($id);

        $post->delete();

        return redirect()->route('query.index');
    }
}

resources/views/staffs/querys/base.blade.php
@extends('staffs/staff.app')


@section('content')
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
    </section>
    @yield('action-content')
    <!-- /.content -->
  </div>
@endsection

resources/views/staffs/querys/create.blade.php
@extends('staffs.querys.base')


@section('action-content')
<div class="content">
            <div class="container-fluid">
    <div class="main-content">

        <!-- You only need this form and the form-basic.css -->

        <div class="form-basic">
                        {!! Form::open(['route'=>'query.store']) !!}

            <div class="form-title-row">
                <h1>Create Query</h1>
            </div>

            <div class="form-row">
                <label>
                    <span> Enter Query </span>
                   {{Form::textarea('question', null)}}
                </label>
            </div>

            <div class="form-row">
                    {{Form::submit('Create Query', array('class'=> 'btn btn-success btn-lg btn-block'))}}
                
            </div>
            {!! Form::close() !!} 

        </div>

    </div>
                        </div>
                </div>
            </div>
        </div>
        
@endsection

resources/views/staffs/querys/edit.blade.php
@extends('staffs.querys.base')


@section('action-content')

        <div class="form-basic">
        	{!! Form::model($querys ,['route'=>['querys.update',$querys->id], 'method' => 'PUT']) !!}

            <div class="form-title-row">
                <h1>Update Query</h1>
            </div>

            <div class="form-row">
                <label> 
                    <span>Answer</span>
                   {{Form::textarea('answer', null)}}
                </label>
            </div>  

            <div class="form-row" style="padding-left: 35%">
            	{{Form::submit('Update Query'), array('class'=> 'btn btn-success btn-lg btn-block')}}
                
            </div>
            {!! Form::close() !!}

        </div>

    </div>

@endsection

resources/views/staffs/querys/index.blade.php
@extends('staffs.querys.base')

@section('action-content')

<div class="row">
	<div class="col-md-10">
		<h3>All Query</h3>
	</div>
	
	<hr>

</div>
<div class="row">
	<div class="col-md-12">
		<table class="table">
			<thead>
				<th>Sn</th>
				<th>Query</th>
				<th>Action</th>
			</thead>
			<tbody>
				@foreach($query as $querys)

				<tr>
					<th>{{$querys->id}}</th>
					<td>{{$querys->question}}</td>
					<td><a href="{{route('querys.show',$querys->id)}}" style="margin: 10px" class="btn btn-primary a-btn-slide-text"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <span><strong>View</strong></span> </a><a href="{{route('querys.edit',$querys->id)}}" class="btn btn-primary a-btn-slide-text"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
        <span><strong>Update</strong></span></a></td>

				</tr>
				@endforeach
			</tbody>
			
		</table>
		<div>
			
		</div>
		
	</div>
</div>
<div class="text-center">
			{{ $query->links() }}
		</div>	

@endsection

resources/views/staffs/querys/show.blade.php
@extends('staffs.querys.base')


@section('action-content')

        <div class="row">
    <div class="col-md-10">
    </div>
    <hr>

</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tc>
                    <th>Sn</th>
                    <th>{{$querys->id}}</th>
                </tc>
            </thead>
            <tbody>
                <tc>
                    <td>Query Title </td>
                    <td>{{$querys->question}}</td>
                </tc>
            </tbody>
            <tbody>
                <tc>
                    <td>Answer </td>
                    <td>{{$querys->answer}}</td>
                </tc>
            </tbody>
            <tbody>
                <tc>
                    <td>Create Date </td>
                    <td>{{date('M j, Y', strtotime($querys->created_at))}}</td>
                </tc>
            </tbody>

            <tbody>
                
                <td><a href="{{route('querys.edit',$querys->id)}}" style="margin: 8px" class="btn btn-primary a-btn-slide-text"> <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        <span><strong>Update</strong></span> </a></td>
            </tbody>

            </tbody>
            
        </table>
        
    </div>
</div>


@endsection